//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustyNail.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public DailyReport()
        {
            this.SalesReports = new HashSet<SalesReport>();
        }
    
        public int Id { get; set; }
        public System.DateTime Day { get; set; }
        public int SuperMarketId { get; set; }
    
        public virtual Supermarket Supermarket { get; set; }
        public virtual ICollection<SalesReport> SalesReports { get; set; }
    }
}
