//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustyNail.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SalesReports = new HashSet<SalesReport>();
        }
    
        public int Id { get; set; }
        public int VendorId { get; set; }
        public string ProductName { get; set; }
        public int MeasureId { get; set; }
        public decimal BasePrice { get; set; }
    
        public virtual Measure Measure { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<SalesReport> SalesReports { get; set; }
    }
}
