//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RustyNail.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Sum { get; set; }
    
        public virtual DailyReport DailyReport { get; set; }
        public virtual Product Product { get; set; }
    }
}
